### ISSUE TITLE
Problem s přidáním paragrafu do Oblíbených

### ISSUE THREAD

**Issue by phracek** [phracek/Katechismus_katolicke_cirkve_iOS#11]
Přidání paragrafu do oblíbených funguje, ale špatně.

touchPoint zde: https://github.com/phracek/Katechismus_katolicke_cirkve_iOS/blob/master/KatechismusKatolickeCirkve/KatechismusKatolickeCirkve/Controllers/ParagraphTableViewController.swift#L301 je sice správně, ale `indexPathForRow` stále bere v potas pouze první položku v tabulce.

@ostatnicky: Nevíš, co jsem udělal špatně? Či co dělám špatně.

**Comment by ostatnicky** [comment]
Vůbec tam nemuší dělat vlastní gesture recognizer, ale table view má metodu `func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)` kde můžeš dělat akce na kliknutí paragraphu. Koukni na pull request #12 ;)
