### ISSUE TITLE
WKWebView a TableView controller

### ISSUE THREAD

**Issue by phracek** [phracek/Katechismus_katolicke_cirkve_iOS#5]
Zde jsem zkousel implementovat WKWebView controller https://github.com/phracek/Katechismus_katolicke_cirkve_iOS/blob/master/KatechismusKatolickeCirkve/KatechismusKatolickeCirkve/Controllers/ParagraphTableViewController.swift

Bohuzel jednotlive ParagraphTableCellView maji stejnou vysku a text neni viditelny.
Dle meho nazoru prechod na TableViewController by prineslo vyhodu ohledne oblibenych paragrafu a dalsi eventualni moznosti, jako poznamky apod.

@ostatnicky Co si myslis o teto issue? Ma smysl? Pokud ano, jak se da nastavit aby paragraphWebView melo vysku podle textu, ktery tam dam. https://github.com/phracek/Katechismus_katolicke_cirkve_iOS/blob/master/KatechismusKatolickeCirkve/KatechismusKatolickeCirkve/Controllers/ParagraphTableViewCell.swift#L15
Neco jsem zkousel zde https://github.com/phracek/Katechismus_katolicke_cirkve_iOS/blob/master/KatechismusKatolickeCirkve/KatechismusKatolickeCirkve/Controllers/ParagraphTableViewController.swift#L72, ale mam tam chybu. Hledal jsem na google, ale neco smysluplneho jsem nasel jeste zde https://stackoverflow.com/questions/32548771/uitableviewcell-with-uiwebview-dynamic-height
Jenze to je UIWebView a ne WKWebView.

Diky za pomoc.

**Comment by ostatnicky** [comment]
Jdeš na do dobře, musíš výšku cellu buď dopočítat nebo tohle ti dělá `tableView.rowHeight = UITableViewAutomaticDimension`. Jen v cellu musíš mít nějakou height contraint, kde budeš nastatovat její `constant`, tzn. `heightConstraint.constant = heightOfWebView` po načtení obsahu ve webview. UIWebView WKWebView by se měly chovat stejně, co vím...

V Kancionálu to dělám takhle. Mám v cellu label. Nastavím text, label se mi automaticky díky `UITableViewAutomaticDimension` sám roztáhne na výšku, takže super. A jak vyřešit italic a bold v textu? Používám na to https://github.com/Raizlabs/BonMot — přidej si ho pomicí podů: https://guides.cocoapods.org/using/getting-started.html

https://github.com/ostatnicky/kancional-ios/blob/2485b221ab35c7a77bea5c4bd1cc3fc4e016426b/Cancional/UI/Song%20Detail/Cells/SongStanzaCell.swift#L105

**Comment by ostatnicky** [comment]
A vyvaroval bych se použítí labelů s attributedText přes celou stránku, třeba `O Aplikaci` se načítá straště dlouho, strašně dlouho se to zprocesovává. Buď to hoď do webview nebo udělej každý odstavec jako samostatný label.

**Comment by phracek** [comment]
Hmm, myslíš do ParagraphTableViewCell?
Jak se to tam dá?
Nebo WKWebView height v Cellu?
Mas nějaký příklad?
Pomohl by mi
